<a href="https://colab.research.google.com/github/Ahmetyldrr/Deep-Learning-Codes/blob/main/1_start_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Kaynak : https://learning.oreilly.com/library/view/deep-learning-with/9781617295263/Text/03.xhtml

# Tensorler

In [ ]:
import torch

In [ ]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [ ]:
a = torch.ones(10)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a[1]

tensor(1.)

In [ ]:
points = torch.zeros(3)
points

tensor([0., 0., 0.])

In [ ]:
points[0]=0
points[1]=1
points[2]=2
points

tensor([0., 1., 2.])

In [ ]:
float(points[1])

1.0

In [ ]:
tensor2d = torch.tensor([[1,2],[2,1],[11,2]])
tensor2d

tensor([[ 1,  2],
        [ 2,  1],
        [11,  2]])

In [ ]:
tensor2d[0]

tensor([1, 2])

In [ ]:
tensor2d[0][0]

tensor(1)

In [ ]:
tensor2d.shape

torch.Size([3, 2])

In [ ]:
tensor2d.size()

torch.Size([3, 2])

## [Named Tensor](https://learning.oreilly.com/library/view/deep-learning-with/9781617295263/Text/03.xhtml#sigil_toc_id_44)

In [ ]:
img_t = torch.randn(5, 5, 3) # shape [channels, rows, columns]
img_t

tensor([[[ 0.3590, -1.4137,  1.9244],
         [ 1.1279,  0.6973,  1.0866],
         [-0.2379, -1.8023, -0.8779],
         [-0.4753,  1.7241,  1.7712],
         [-1.3038, -0.3960,  0.9144]],

        [[-0.1277,  0.2716, -1.6823],
         [ 0.4882,  0.3324, -0.8975],
         [ 0.9801,  0.3621,  0.5656],
         [-1.9203, -0.6164, -1.3620],
         [-0.4149,  0.4501,  0.1924]],

        [[-0.8119,  1.5660,  0.6353],
         [ 1.3473,  0.9650,  1.4185],
         [ 0.9404, -0.0262,  0.9709],
         [ 1.4638,  0.6574,  0.7038],
         [ 0.0421, -0.4358, -1.9744]],

        [[-1.0100, -0.1611,  1.0769],
         [-2.2089,  0.1152,  1.1350],
         [ 1.6404,  0.1877,  0.2309],
         [-1.0912,  0.4156, -1.1200],
         [-0.9312,  0.0677, -2.1506]],

        [[ 0.5159, -0.5292,  0.2202],
         [ 1.3015, -1.6155,  0.6878],
         [-1.1045,  1.1702, -0.8868],
         [ 1.1209,  0.4272,  0.9944],
         [-0.0410,  1.1899, -1.0008]]])

In [ ]:
weights = torch.tensor([10.0, 10.0, 10.0])
weights

tensor([10., 10., 10.])

In [ ]:
k = img_t * weights
k

tensor([[[  3.5904, -14.1368,  19.2438],
         [ 11.2792,   6.9731,  10.8659],
         [ -2.3787, -18.0232,  -8.7792],
         [ -4.7535,  17.2407,  17.7120],
         [-13.0379,  -3.9602,   9.1444]],

        [[ -1.2774,   2.7158, -16.8226],
         [  4.8820,   3.3244,  -8.9749],
         [  9.8009,   3.6209,   5.6563],
         [-19.2026,  -6.1644, -13.6198],
         [ -4.1492,   4.5005,   1.9239]],

        [[ -8.1188,  15.6598,   6.3528],
         [ 13.4732,   9.6497,  14.1850],
         [  9.4040,  -0.2624,   9.7091],
         [ 14.6383,   6.5744,   7.0377],
         [  0.4215,  -4.3581, -19.7438]],

        [[-10.1000,  -1.6113,  10.7688],
         [-22.0894,   1.1520,  11.3497],
         [ 16.4039,   1.8772,   2.3091],
         [-10.9118,   4.1562, -11.1998],
         [ -9.3120,   0.6768, -21.5055]],

        [[  5.1589,  -5.2919,   2.2015],
         [ 13.0152, -16.1550,   6.8775],
         [-11.0450,  11.7023,  -8.8677],
         [ 11.2087,   4.2715,   9.9438],
        

In [ ]:
img_t = torch.randn(3,3,3,3) # shape [channels, rows, columns]
img_t

l =  weights @ img_t
l


tensor([[[-22.7730, -29.8047,  15.9983],
         [-36.2726,  -0.3660,  37.5874],
         [ -4.0136,  16.6771, -39.4014]],

        [[-22.6076,   0.4477,   4.1722],
         [-16.9684, -12.1960, -26.4998],
         [-25.6591,  -8.4516, -39.3284]],

        [[ -6.8226, -12.2566, -24.9011],
         [ 11.5152, -29.1154,   9.0611],
         [ -8.0792,   2.2579,  -8.5166]]])

In [ ]:
img_t = torch.randn(3) # shape [channels, rows, columns]

m =  weights.dot(img_t)
m

tensor(-28.7676)

In [ ]:
img_t = torch.randn(3) # shape [channels, rows, columns]

m =  img_t.dot(weights)
m

tensor(-2.8507)

In [ ]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[ 0.0648, -0.7913, -1.1642, -1.2950,  1.2289],
          [-0.0259, -1.6182, -1.5546,  0.5373, -0.9952],
          [ 0.0426, -0.8190,  0.2010,  0.6762,  0.9382],
          [ 0.7667, -0.5542, -0.1445,  0.0835,  0.0774],
          [ 1.5266, -1.8295, -1.0243, -0.7724, -0.2592]],

         [[-1.1399,  0.0904,  1.4124, -0.2269,  0.0846],
          [ 0.6971,  0.9064,  1.2420,  1.5686,  0.8763],
          [ 0.5400,  0.6708, -1.7354, -1.3205,  0.8782],
          [-2.2594,  1.0050,  1.1244, -0.0686,  1.2173],
          [-1.6841, -0.2568,  0.4688,  0.7828,  0.5287]],

         [[ 2.5700,  0.7983, -0.0091, -0.3377, -2.0504],
          [-0.1031, -3.6010, -0.4290, -0.6380, -0.5077],
          [ 0.1460,  0.4123,  1.6898,  0.5845,  1.4718],
          [-0.3406, -0.3153,  1.1893,  0.4110,  1.0527],
          [-0.1207,  0.2690, -0.7351, -1.2827,  0.8784]]],


        [[[ 0.8556,  0.6574, -1.6834,  1.1801, -0.1582],
          [ 0.8672,  0.1691,  0.6584, -0.6237,  0.6045],
          [-0.0229,  1.

In [ ]:

img_t=torch.rand(3,4,5)  # shape [channels, rows, columns]
img_t

tensor([[[0.9325, 0.1835, 0.0503, 0.0925, 0.8571],
         [0.7469, 0.1788, 0.5682, 0.3663, 0.7488],
         [0.5710, 0.6492, 0.6789, 0.1712, 0.6959],
         [0.1010, 0.8735, 0.5975, 0.5453, 0.7591]],

        [[0.3214, 0.1938, 0.2672, 0.9427, 0.9612],
         [0.3644, 0.2987, 0.6293, 0.2117, 0.3122],
         [0.2349, 0.4039, 0.2715, 0.4341, 0.7117],
         [0.9742, 0.3800, 0.4291, 0.8201, 0.3012]],

        [[0.1340, 0.2059, 0.8479, 0.0165, 0.4571],
         [0.4142, 0.3529, 0.5113, 0.0488, 0.9273],
         [0.0534, 0.9209, 0.5177, 0.3158, 0.2381],
         [0.8691, 0.9073, 0.0205, 0.6333, 0.6700]]])

In [ ]:
test_mean = torch.tensor([[[10.0, 1.0,1.0,1.0,1.0],
                    [2.0, 2.0, 2.0, 2.0,2.0],
                    [3.0,3.0, 3.0,3.0, 3.0],
                    [4.0,4.0,4.0,4.0, 4.0]],

                    [[1.0, 1.0,1.0,1.0,1.0],
                    [2.0, 2.0, 2.0, 2.0,2.0],
                    [3.0,3.0, 3.0,3.0, 3.0],
                    [4.0,4.0,4.0,4.0, 4.0]],

                   [[1.0, 1.0,1.0,1.0,1.0],
                    [2.0, 2.0, 2.0, 2.0,2.0],
                    [3.0,3.0, 3.0,3.0, 3.0],
                    [4.0,4.0,4.0,4.0, 4.0]],


                   [[1.0, 1.0,1.0,1.0,1.0],
                    [2.0, 2.0, 2.0, 2.0,2.0],
                    [3.0,3.0, 3.0,3.0, 3.0],
                    [4.0,4.0,4.0,4.0, 4.0]]]

                   )

test_mean

tensor([[[10.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.]],

        [[ 1.,  1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.]]])

In [ ]:
test_mean.shape

torch.Size([4, 4, 5])

In [ ]:
img_gray_naive = test_mean.mean(-1)
img_gray_naive

tensor([[2.8000, 2.0000, 3.0000, 4.0000],
        [1.0000, 2.0000, 3.0000, 4.0000],
        [1.0000, 2.0000, 3.0000, 4.0000],
        [1.0000, 2.0000, 3.0000, 4.0000]])

In [ ]:
img_gray_naive = test_mean.mean(-2)
img_gray_naive

tensor([[4.7500, 2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000, 2.5000, 2.5000]])

In [ ]:
img_gray_naive = test_mean.mean(-3)
img_gray_naive

tensor([[3.2500, 1.0000, 1.0000, 1.0000, 1.0000],
        [2.0000, 2.0000, 2.0000, 2.0000, 2.0000],
        [3.0000, 3.0000, 3.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 4.0000, 4.0000, 4.0000]])

## Managing a tensor’s dtype attribute

In [ ]:
import torch
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [ ]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [ ]:
short_points.dtype

torch.int16

In [ ]:
double_points = torch.zeros(10, 2).double()
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [ ]:
short_points = torch.ones(10, 2).short()
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [ ]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [ ]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [ ]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

## Transpose High Dimension

In [ ]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [ ]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
transpose_t = some_t.transpose(0, 2)
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
transpose_t.shape

torch.Size([5, 4, 3])

## Managing a tensor’s device attribute

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cpu')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

## NumPy interoperability

In [ ]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Serializing tensors

In [ ]:
torch.save(points, '/content/sample_data/ourpoints.t')

In [ ]:
with open('/content/sample_data/ourpoints.t','wb') as f:
   torch.save(points, f)

In [ ]:
points = torch.load('/content/sample_data/ourpoints.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])